apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8081"
  AMQP_URL: "amqp://guess:guess@rabbitmq:5672/"
  STRIPE_SUCCESS_URL: "http://localhost:3000?payment=success"
  STRIPE_CANCEL_URL: "http://localhost:3000?payment=cancel"
  STRIPE_SUCCESS_URL: "http://localhost:3000?payment=success"
  STRIPE_CANCEL_URL: "http://localhost:3000?payment=cancel"
  STRIPE_SECRET_KEY: "pk_test_51S4MQ1KNu9shlLQmNPUDJAHvV3BtacCEkBXZO3UYTmZfTDE9BL5s8I1rCAA4rygYA6lZFAgB4IBIFQW5SFUetNsM00Nxnx6Gvj"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51S4MQ1KNu9shlLQmNPUDJAHvV3BtacCEkBXZO3UYTmZfTDE9BL5s8I1rCAA4rygYA6lZFAgB4IBIFQW5SFUetNsM00Nxnx6Gvj"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "riderdb"
  POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/riderdb?sslmode=disable"
